use_frameworks!

platform :ios, '9.0'

target 'FuseSensorsAnalytics_Example' do
  pod 'FuseSensorsAnalytics', :path => '../'

  target 'FuseSensorsAnalytics_Tests' do
    inherit! :search_paths

    
  end
end
